name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          docker build -t wine .
          docker run wine
          docker run \
            --mount type=bind,source=${PWD}/data,target=/home/trainer/app/data \
            --mount type=bind,source=${PWD}/metrics,target=/home/trainer/app/metrics
            wine
          cat metrics/metrics.json >> report.md
          cml-send-comment report.md