name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bash install-gcloud.sh
          cat ${{ secrets.GITHUB_TOKEN }} > sa.json
          gcloud auth activate-service-account --key-file=sa.json

          # Your ML workflow goes here
          docker build -t wine .
          dvc pull
          dvc repro

          cml-send-comment report.md